# Generated by Django 4.1.7 on 2023-02-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QuestionAnswerData",
            fields=[
                (
                    "id",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("question", models.CharField(max_length=256)),
                ("answer", models.CharField(max_length=256)),
                ("studyYear", models.IntegerField(max_length=1)),
                ("subject", models.CharField(max_length=256)),
                ("date", models.DateTimeField()),
                ("reaction", models.BooleanField()),
            ],
        ),
    ]
